language: node_js
sudo: false
node_js: 7
cache:
  directories:
  - node_modules
before_script:
- node --version
- npm --version
- npm install -g grunt-cli
script:
- npm run test-travis
before_deploy:
- npm install
- npm run build
- npm run dist
deploy:
  provider: npm
  email: ashdevfr@gmail.com
  api_key:
    secure: C5NIZoZpXp0tbEBXXRckjs/W8qOugedzXl/AMJDOWH+HqaYXdZABU5fV0ETmD+8AKeQa93LptEOb0ULYOzgV/hUsKZOVmztlOzh6ahKVYQ9HlN/8M84EQn5FC1c5ykPACxOjWvc8EnM/HTh+gG9tXnrz8MXGae5Dd8n1SQoMsqPnm4POCST12jSFWJ51Hp2bv9W3CeaoBVbRRPgvqMgrA4htNRaQcxlYPGmpQuo2zLdeVbS+SiiM55EU5RM0BaiHf3drNiXurh/dlWMhb+pHduCUTLO+r8lOvXuR+lNrwJZB+8RXfVuRVpeivX+Tcu5KaFgsr1iQc94NQuQ6/KgPYPVdyXyRjHqIAMep7+nccWblZoTuUlNk0r+jWT4lnDzahy9vLFT6077zKZqnUrYAJJyl2/xPTFRwkSvEnPoY4p4CJ69e/eqec0diq5xMLMfEVYA6hv8z8Y/A2WVXWC/5qCEGMbEXFctJmcXDkzHixkwwX+mGMYTUQzBehdNzHfTM5rYpvWIwNDLTZOz+4A1Cwue0lCpt3DuP3f331I7ioAGs5N6Rh8qcXoFqJNPCaOqM4kdlbNCJqI9mYC+LnuAayOY0dvheIOaBSVl4N3HqUHDByO+rPPLOjQqCgDvmrWl4unOHRARN0WplLTEL5a39FqtMzwKAFbb4WOQSWR/MHnY=
  on:
    tags: true
    branch: develop
after_success:
- npm run coveralls
